---

- name: create directory for keys and certs
  file: >
    state=directory
    dest={{ openvpn_common_config_dir }}/{{ openvpn_client.client_name }}@{{ openvpn_client.vpn_name }}
    mode=0755
  notify: Restart OpenVPN server/clients

- name: deploy ca cert
  copy: >
    content="{{ openvpn_client.ca_cert }}"
    dest={{ openvpn_common_config_dir }}/{{ openvpn_client.client_name }}@{{ openvpn_client.vpn_name }}/ca.crt
    mode=0640
  notify: Restart OpenVPN server/clients

- name: deploy client cert
  copy: >
    content="{{ openvpn_client.client_cert }}"
    dest={{ openvpn_common_config_dir }}/{{ openvpn_client.client_name }}@{{ openvpn_client.vpn_name }}/client.crt
    mode=0640
  notify: Restart OpenVPN server/clients

- name: deploy client key
  copy: >
    content="{{ openvpn_client.client_key }}"
    dest={{ openvpn_common_config_dir }}/{{ openvpn_client.client_name }}@{{ openvpn_client.vpn_name }}/client.key
    mode=0600
  notify: Restart OpenVPN server/clients

- name: deploy crl
  copy: content="{{ openvpn_client.crl }}" dest={{ openvpn_common_config_dir }}/{{ openvpn_client.client_name }}@{{ openvpn_client.vpn_name }}/crl.pem mode=0644
  when: >
    "crl" in openvpn_client
  notify: Restart OpenVPN server/clients

- name: deploy tls auth key
  copy: content="{{ openvpn_client.ta_key }}" dest={{ openvpn_common_config_dir }}/{{ openvpn_client.client_name }}@{{ openvpn_client.vpn_name }}/ta.key mode=0600
  when: >
    "ta_key" in openvpn_client
  notify: Restart OpenVPN server/clients

- name: deploy config file
  template: >
    src=client.conf.j2
    dest={{ openvpn_common_config_dir }}/{{ openvpn_client.client_name }}@{{ openvpn_client.vpn_name }}.conf
    mode=0640
  notify: Restart OpenVPN server/clients
