---

- name: Get installed packages
  dnf:
    list: installed
  register: rpmfusion_package_list
  check_mode: no

- name: Install rpmfusion free configuration packages
  dnf:
    name: 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_lsb.release }}.noarch.rpm'
    state: present
  when: rpmfusion_package_list.results|selectattr("name", "equalto", "rpmfusion-free-release")|list|length == 0

- name: Install rpmfusion nonfree configuration packages
  dnf:
    name: 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_lsb.release }}.noarch.rpm'
    state: present
  when: rpmfusion_package_list.results|selectattr("name", "equalto", "rpmfusion-nonfree-release")|list|length == 0
