---

- name: create directory for keys and certs
  file: >
    state=directory
    dest={{ openvpn_common_config_dir }}/{{ openvpn_server.server_name }}@{{ openvpn_server.vpn_name }}
    mode=0755
  notify: Restart OpenVPN server/clients

- name: create client config directory
  file: >
    state=directory
    dest={{ openvpn_common_config_dir }}/{{ openvpn_server.server_name }}@{{ openvpn_server.vpn_name }}/ccd
    mode=0755
  when: >
    "client_configs" in openvpn_server
  notify: Restart OpenVPN server/clients

- name: deploy client configs
  template: >
    src=client-config.j2
    dest={{ openvpn_common_config_dir }}/{{ openvpn_server.server_name }}@{{ openvpn_server.vpn_name }}/ccd/{{ item.key }}
    mode=0640
  with_dict: openvpn_server.client_configs | default({})
  notify: Restart OpenVPN server/clients

- name: deploy ca cert
  copy: >
    content="{{ openvpn_server.ca_cert }}"
    dest={{ openvpn_common_config_dir }}/{{ openvpn_server.server_name }}@{{ openvpn_server.vpn_name }}/ca.crt
    mode=0640
  notify: Restart OpenVPN server/clients

- name: deploy server cert
  copy: >
    content="{{ openvpn_server.server_cert }}"
    dest={{ openvpn_common_config_dir }}/{{ openvpn_server.server_name }}@{{ openvpn_server.vpn_name }}/server.crt
    mode=0640
  notify: Restart OpenVPN server/clients

- name: deploy server key
  copy: >
    content="{{ openvpn_server.server_key }}"
    dest={{ openvpn_common_config_dir }}/{{ openvpn_server.server_name }}@{{ openvpn_server.vpn_name }}/server.key
    mode=0600
  notify: Restart OpenVPN server/clients

- name: deploy dh params
  copy: >
    content="{{ openvpn_server.dh_params }}"
    dest={{ openvpn_common_config_dir }}/{{ openvpn_server.server_name }}@{{ openvpn_server.vpn_name }}/dh.pem
    mode=0600
  notify: Restart OpenVPN server/clients

- name: deploy crl
  copy: content="{{ openvpn_server.crl }}" dest={{ openvpn_common_config_dir }}/{{ openvpn_server.server_name }}@{{ openvpn_server.vpn_name }}/crl.pem mode=0644
  when: >
    "crl" in openvpn_server
  notify: Restart OpenVPN server/clients

- name: deploy tls auth key
  copy: content="{{ openvpn_server.ta_key }}" dest={{ openvpn_common_config_dir }}/{{ openvpn_server.server_name }}@{{ openvpn_server.vpn_name }}/ta.key mode=0600
  when: >
    "ta_key" in openvpn_server
  notify: Restart OpenVPN server/clients

- name: deploy config file
  template: >
    src=server.conf.j2
    dest={{ openvpn_common_config_dir }}/{{ openvpn_server.server_name }}@{{ openvpn_server.vpn_name }}.conf
    mode=0640
  notify: Restart OpenVPN server/clients
