---

- name: Get installed packages
  dnf:
    list: installed
  register: vagrant_package_list
  check_mode: no

- name: Install Vagrant
  dnf:
    name: 'https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.rpm'
    state: present
  when: vagrant_package_list.results|selectattr("nevra", "equalto", "1:vagrant-" + vagrant_version + "-1.x86_64")|list|length == 0
