---

dns_rndc_key: '{{ secrets_dns_rndc_key }}'

dns_zones:

  - domain: km21007.keymachine.de
    ip: 84.19.186.99
    # TODO: how to generate the serial automatically?
    serial: 2015071200
    ttl: 86400
    # TODO: allow normal email addresses and replace '.' and '@' with jinja2
    admin_email: krille.thomaskrille.de

    # first one is primary
    name_servers:
      - ns.km21007.keymachine.de
      - ns2.km21007.keymachine.de

    a_records:
      - name: ns.km21007.keymachine.de
        ip: 84.19.186.99
      - name: ns2.km21007.keymachine.de
        ip: 84.19.187.99


  - domain: thomaskrille.de
    ip: 84.19.186.99
    # TODO: how to generate the serial automatically?
    serial: 2015071200
    ttl: 86400
    # TODO: allow normal email addresses and replace '.' and '@' with jinja2
    admin_email: krille.thomaskrille.de

    # first one is primary
    name_servers:
      - ns.km21007.keymachine.de
      - ns2.km21007.keymachine.de

    aliases:
      - name: www.thomaskrille.de
        cname: thomaskrille.de

    mx_records:
      - priority: 10
        server: ASPMX.L.GOOGLE.COM
      - priority: 20
        server: ALT1.ASPMX.L.GOOGLE.COM
      - priority: 20
        server: ALT2.ASPMX.L.GOOGLE.COM
      - priority: 30
        server: ALT2.ASPMX.L.GOOGLE.COM
      - priority: 30
        server: ASPMX3.GOOGLEMAIL.COM
      - priority: 30
        server: ASPMX4.GOOGLEMAIL.COM
      - priority: 30
        server: ASPMX5.GOOGLEMAIL.COM


  - domain: t10e.de
    ip: 84.19.187.99
    # TODO: how to generate the serial automatically?
    serial: 2015071200
    ttl: 86400
    # TODO: allow normal email addresses and replace '.' and '@' with jinja2
    admin_email: krille.thomaskrille.de

    # first one is primary
    name_servers:
      - ns.km21007.keymachine.de
      - ns2.km21007.keymachine.de

    aliases:
      - name: www.t10e.de
        cname: t10e.de
