---

- name: install default packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  when: ansible_pkg_mgr == "apt"
  with_items: libvirt_packages
  notify: update guestfs appliance

- name: check vagrant-libvirt version
  shell: vagrant plugin list | grep '^vagrant-libvirt' | awk '{print $2}' | sed -e 's/.$//' -e 's/^.//'
  always_run: yes
  ignore_errors: yes
  changed_when: False
  register: vagrant_libvirt_version_result

- name: install vagrant-libvirt
  command: vagrant plugin install --plugin-version {{ libvirt_vagrant_libvirt_version }} vagrant-libvirt
  when: vagrant_libvirt_version_result.stdout != libvirt_vagrant_libvirt_version

- name: check vagrant-mutate version
  shell: vagrant plugin list | grep '^vagrant-mutate' | awk '{print $2}' | sed -e 's/.$//' -e 's/^.//'
  always_run: yes
  ignore_errors: yes
  changed_when: False
  register: vagrant_mutate_version_result

- name: install vagrant-mutate
  command: vagrant plugin install --plugin-version {{ libvirt_vagrant_mutate_version }} vagrant-mutate
  when: vagrant_mutate_version_result.stdout != libvirt_vagrant_mutate_version
