---

- name: Create folder for custom templates
  file:
    state: directory
    path: /usr/local/psa/admin/conf/templates/custom/webmail
    owner: root
    group: root
    mode: 0755

- name: Create temporary file to hold override config
  tempfile:
    state: file
    suffix: ansible_plesk_webmail_tls
  register: plesk_webmail_tls_tempfile
  check_mode: no
  changed_when: False

- name: Copy original template file
  copy:
    remote_src: True
    src: /usr/local/psa/admin/conf/templates/default/webmail/webmail.php
    dest: '{{ plesk_webmail_tls_tempfile.path }}'
  check_mode: no
  changed_when: False

- name: Redirect webmail HTTP to HTTPS in temporary template file
  replace:
    path: '{{ plesk_webmail_tls_tempfile.path }}'
    regexp: '(<\/VirtualHost>[\S\s]*<IfModule mod_ssl\.c>)'
    replace: |-
      RewriteEngine On
      RewriteCond %{HTTPS} off
      RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

      \1
  check_mode: no
  changed_when: False

- name: Install custom template file
  copy:
    remote_src: True
    src: '{{ plesk_webmail_tls_tempfile.path }}'
    dest: /usr/local/psa/admin/conf/templates/custom/webmail/webmail.php
  notify:
    - Reconfigure all domains
