---

- name: deplpoy rndc key
  template: src=rndc.key.j2
              dest=/etc/bind/rndc.key
              owner=bind group=bind mode=0640
  notify:
    - restart dns server

- name: deploy bind options
  template: src=named.conf.options.j2
              dest=/etc/bind/named.conf.options
              owner=root group=bind mode=0644
  notify:
    - restart dns server

- name: deploy local config and zones
  template: src=named.conf.local.j2
              dest=/etc/bind/named.conf.local
              owner=root group=bind mode=0644
  notify:
    - restart dns server

- name: create log dir
  file: path=/var/log/bind state=directory
          owner=bind group=bind mode=0755

- name: deploy logging config
  copy: src=named.conf.log
              dest=/etc/bind/named.conf.log
              owner=root group=bind mode=0644
  notify:
    - restart dns server

- name: deploy zone files
  template: src=zone_file.j2
              dest=/var/lib/bind/db.{{ item.domain }}
              owner=root group=bind mode=0644
  with_items: dns_zones
  notify:
    - restart dns server
