---

- name: common stuff for all nodes
  hosts: all
  roles:
    - role: franklinkim.timezone
      timezone: 'Europe/Berlin'
      when: ansible_os_family == 'Debian'
    - role: apt
      when: ansible_pkg_mgr == "apt"
    - role: packages
    - role: ssh_keys
    - role: zsh
    - role: dotfiles
