---

- name: Custom tasks for NAS
  hosts: nas

  roles:
    - role: debops.apt_preferences
      tags:
        - apt_preferences
    - role: network_interface
    - role: dnsmasq
    - role: users
    - role: samba
    - role: apache
