---

- name: Common stuff for servers
  hosts: server
  pre_tasks:
    - name: Generate locale en_US.UTF-8
      locale_gen: name=en_US.UTF-8
      tags: locale_gen
    - name: Generate locale de_DE.UTF-8
      locale_gen: name=de_DE.UTF-8
      tags: locale_gen
  roles:
    - role: franklinkim.timezone
      timezone: 'Europe/Berlin'
      when: ansible_os_family == 'Debian'
    - role: apt
      when: ansible_pkg_mgr == "apt"
    - role: packages
    - role: ssh_keys
    - role: zsh

- name: Custom tasks for NAS
  hosts: nas

  roles:
    - role: debops.apt_preferences
      tags:
        - apt_preferences
    - role: network_interface
    - role: users
    - role: samba
    - role: apache
    - role: smtp_relay
    - role: mdadm_mail
