---

- name: Get installed packages
  dnf:
    list: installed
  register: google_chrome_package_list
  check_mode: no

- name: Install Google Chrome (Stable)
  dnf:
    name: 'https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm'
    state: present
  when: google_chrome_package_list.results|selectattr("name", "equalto", "google-chrome-stable")|list|length == 0
